return {
  {Image="99NIAF.png", GameName="99 Nights In A Forest", LastUpdated="1/11/2026", Status="Working"},
  {Image="Adopt_Me.png", GameName="Adopt Me", LastUpdated="1/11/2026", Status="Working"},
  {Image="BABFT.png", GameName="Build A Boat", LastUpdated="Long Ago", Status="Unkown"},
  {Image="Blade_Ball.png", GameName="Blade Ball", LastUpdated="1/31/2026", Status="Working"},
  {Image="Bloxburg.png", GameName="BloxBurg", LastUpdated="Long Ago", Status="Working"},
  {Image="Brainrot_Jenga_Tower.png", GameName="Brainrot Jenga Tower!", LastUpdated="2/1/2026", Status="Working"},
  {Image="Cheese_Escape.png", GameName="Cheese Escape", LastUpdated="2/1/2026", Status="Working"},
  {Image="Color_Block.png", GameName="Color Block", LastUpdated="2/1/2026", Status="Working"},
  {Image="Critical_Fantasy.png", GameName="Critical Fantasy", LastUpdated="2/1/2026", Status="Working"},
  {Image="Dandys_World.png", GameName="Dandys World", LastUpdated="1/11/2026", Status="Working"},
  {Image="Dead_Rails.png", GameName="Dead Rails", LastUpdated="Long Ago", Status="Working"},
  {Image="Dig_To_Earths_Core.png", GameName="Dig To Earths Core", LastUpdated="2/1/2026", Status="Working"},
  {Image="Dont_Leave_The_Circle.png", GameName="Dont Leave The Circle", LastUpdated="2/1/2026", Status="Working"},
  {Image="Driving_Empire.png", GameName="Driving Empire", LastUpdated="1/11/2026", Status="Working"},
  {Image="Epic_Minigames.png", GameName="Epic Minigames", LastUpdated="2/1/2026", Status="Working"},
  {Image="Evade.png", GameName="Evade", LastUpdated="1/31/2026", Status="Working"},
  {Image="Fish_It.png", GameName="Fish It", LastUpdated="Long Ago", Status="Working"},
  {Image="Fisch.png", GameName="Fisch", LastUpdated="12/27/2025", Status="Working"},
  {Image="Flee_The_Facility.png", GameName="Flee The Facility", LastUpdated="0:00:0000", Status="Working"},
  {Image="Forsaken.png", GameName="Forsaken", LastUpdated="Long Ago", Status="Working"},
  {Image="Grace.png", GameName="Grace", LastUpdated="Awaiting Update", Status="Unknown"},
  {Image="Grow_A_Garden.png", GameName="Grow a Garden", LastUpdated="Long Ago", Status="Working"},
  {Image="Guts_&_Blackpowder.png", GameName="Guts & Blackpowder", LastUpdated="Long Ago", Status="Broken"},
  {Image="Hide_N_Seek_Extreme.png", GameName="Hide N Seek Extreme", LastUpdated="2/1/2026", Status="Working"},
  {Image="Hide_Or_Die.png", GameName="Hide Or Die", LastUpdated="2/1/2026", Status="Working"},
  {Image="Laundry_Simulator.png", GameName="Laundry Simulator", LastUpdated="2/1/2026", Status="Working"},
  {Image="Lootify.png", GameName="Lootify", LastUpdated="2/1/2026", Status="Working"},
  {Image="Motorush.png", GameName="Motorush", LastUpdated="2/1/2026", Status="Working"},
  {Image="Murder_Mystery_2", GameName="Murder Mystery 2", LastUpdated="1/3/2026", Status="Working"},
  {Image="Natural_Disaster.png", GameName="Natural Disaster Survival", LastUpdated="2/1/2026", Status="Working"},
  {Image="Ninja_Legends.png", GameName="Ninja Legends", LastUpdated="2/1/2026", Status="Working"},
  {Image="Pet_Simulator_99.png", GameName="Pet Simulator 99", LastUpdated="Long Ago", Status="Working"},
  {Image="Piggy.png", GameName="Piggy", LastUpdated="1/11/2026", Status="Working"},
  {Image="Plants_Vs_Brainrots.png", GameName="Plants vs Brainrots", LastUpdated="1/3/2026", Status="Working"},
  {Image="Project_Lazarus.png", GameName="Project Lazarus", LastUpdated="2/2/2026", Status="Working"},
  {Image="Restaurant_Tycoon_2.png", GameName="Restaurant Tycoon 2", LastUpdated="2/1/2026", Status="Working"},
  {Image="Rocitizens.png", GameName="Rocitizens", LastUpdated="1/30/2026", Status="Working"},
  {Image="Royal_High.png", GameName="Royal High", LastUpdated="Long Ago", Status="Unknown"},
  {Image="Saber_Simulator.png", GameName="Saber Simulator", LastUpdated="2/1/2026", Status="Working"},
  {Image="Slime_Slayer_Online.png", GameName="Slime Slayer", LastUpdated="Long Ago", Status="Broken"},
  {Image="Speed_Run_4.png", GameName="Speed Run 4", LastUpdated="2/1/2026", Status="Working"},
  {Image="Tower_Of_Hell.png", GameName="Tower Of Hell", LastUpdated="2/1/2026", Status="Working"},
  {Image="Underground_War_2.png", GameName="Underground War 2.0", LastUpdated="1/30/2026", Status="Working"},
  {Image="Vehicle Legends.png", GameName="Vehicle Legends", LastUpdated="2/1/2026", Status="Working"},
  {Image="Word_Bomb.png", GameName="Word Bomb", LastUpdated="2/1/2026", Status="Working"},
  {Image="Zombie_Attack.png", GameName="Zombie Attack", LastUpdated="2/1/2026", Status="Working"}
}
