return {
  {Image="", GameName="Murder Mystery 2", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Driving Empire", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Dandys World", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Grow a Garden", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Piggy", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Forsaken", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Build A Boat", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="99 Nights In A Forest", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Adopt Me", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Plants vs Brainrots", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Fish It", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Fisch", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="BloxBurg", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Pet Simulator 99", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Project Lazarus", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Flee The Facility", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Motorush", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Vehicle Legends", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Restaurant Tycoon 2", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Evade", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Royal High", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Impossible Squid Game Glass Bridge 2", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Robbing Tycoon", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Natural Disaster Survival", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Slime Slayer", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Dungeon Quest", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Hide N Seek Extreme", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Zombie Attack", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Tower Of Hell", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Ninja Legends", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Shrimp Games", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Word Bomb", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Underground War 2.0", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Blox Hunt", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Pick A Side", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Tsunami Game", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Speed Run 4", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Hide Or Die", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Grow Trees", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Mine", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Dig To Earths Core", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Steal A Garden", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Paper Plane Simulator", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Untitled Digging Game", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Grow Crystals", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Infinite Mining Incremental", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Color Block", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Skinwalkers", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Critical Fantasy", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Lootify", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Dungeon Lootify", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Rocitizens", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Blade Ball", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Laundry Simulator", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Cheese Escape", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Dead Rails", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Guts & Blackpowder", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Bubble Gum Simulator Infinity", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Dont Wake The Brainrot", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Click To Aura Farm", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Trade a Brainrot", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Sticks Incremental", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Brainrot Jenga Tower!", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Get Down!", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Rebirth Champions X", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Clean A House", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Epic Minigames", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Grace", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Labubu Glass Bridge", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Be a Beggar!", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Touch Soccer", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Saber Simulator", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Rebirth Champions Ultimate", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Reaper Simulator", LastUpdated="0:00:0000", Status="Working"},
  {Image="", GameName="Dont Leave The Circle", LastUpdated="0:00:0000", Status="Working"}
}
